[package]
name = "graph-revs-log-for-path"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4.42"
clap = "4.5.47"
dsi-progress-logger = "0.8.2"
env_logger = "0.11.8"
log = "0.4.28"
swh-graph = "8.0.4"
