---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-checks-pvc
  namespace: swh-cassandra
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-checks
  name: cassandra-checks
  namespace: swh-cassandra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cassandra-checks
  template:
    metadata:
      labels:
        app: cassandra-checks
    spec:
      containers:
        - name: cassandra-checks
          command:
          - /bin/sleep
          - infinity
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: debian:bookworm
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /volume
            name: cassandra-checks-volume
      volumes:
        - name: cassandra-checks-volume
          persistentVolumeClaim:
            claimName: cassandra-checks-pvc
