{
 "title": "System",
 "time": { "from": "2021-06-16T17:50:48.317Z", "to": "2021-06-17T06:28:54.812Z" },
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "Node",
    "query": {
     "query": "label_values(node_load1, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nodes" },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$nodes\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$nodes\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$nodes\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"$nodes\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$nodes\"} - node_memory_MemFree_bytes{instance=~\"$nodes\"} - node_memory_Buffers_bytes{instance=~\"$nodes\"}  - node_memory_Cached_bytes{instance=~\"$nodes\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$nodes'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$nodes'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$nodes'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$nodes\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second in - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second out - {{device}}"
    }
   ]
  },
  { "title": "$nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$nodes\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$nodes\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$nodes\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"$nodes\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$nodes\"} - node_memory_MemFree_bytes{instance=~\"$nodes\"} - node_memory_Buffers_bytes{instance=~\"$nodes\"}  - node_memory_Cached_bytes{instance=~\"$nodes\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$nodes'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$nodes'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$nodes'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$nodes\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second in - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second out - {{device}}"
    }
   ]
  },
  { "title": "$nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$nodes\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$nodes\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$nodes\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"$nodes\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$nodes\"} - node_memory_MemFree_bytes{instance=~\"$nodes\"} - node_memory_Buffers_bytes{instance=~\"$nodes\"}  - node_memory_Cached_bytes{instance=~\"$nodes\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$nodes'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$nodes'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$nodes'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$nodes\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second in - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second out - {{device}}"
    }
   ]
  },
  { "title": "$nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$nodes\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$nodes\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$nodes\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 85 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"$nodes\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$nodes\"} - node_memory_MemFree_bytes{instance=~\"$nodes\"} - node_memory_Buffers_bytes{instance=~\"$nodes\"}  - node_memory_Cached_bytes{instance=~\"$nodes\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$nodes'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$nodes'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$nodes'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 94 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$nodes\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second in - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$nodes\"}[5m]) * 8",
     "legendFormat": "bytes per second out - {{device}}"
    }
   ]
  }
 ]
}