# Default values for worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

amqp:
  user: guest
  password: guest
  host: amqp

storage:
  host: swh-storage

loader:
  name: loaders
  type: <override>

swh:
  loader:
    image: softwareheritage/loaders
    version: 2022-04-28
    replicas:
      min: 1
      max: 10

