@startuml "vpn temporary"
nwdiag {

    network VLAN440 {
        address = "192.168.100.0/24"

        louvre [address = "192.168.100.1"]
        opnsense [address = "192.168.100.130"]

    }


    network openvpn {
        address = "192.168.102.0/23"

        opnsense [address = "192.168.102.1"]

        user [address="192.168.102.x" description = "<&people*4.5>\n users"];
    }

    network legacy_openvpn {
        address = "192.168.101.0/24"

        louvre [address = "192.168.101.1"]
        users [address="192.168.101.x" description = "<&people*4.5>\n users"];
    }

    network ipsec {
        address = "192.168.200.1/24"

        azure_nodes [address="192.168.200.x" description = "<&cloudy*4.5>\n Azure"]

        louvre
        opnsense
    }

    network staging {
        address = "192.168.130.1/24"

        opnsense [address="192.168.130.1"]
    }

    network admin {
        address = "192.168.50.1/24"

        opnsense [address="192.168.50.1"]
    }

    legend
    Temporary configuration during tests
    end legend
}

@enduml
