[package]
name = "graph-object-size"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.26"
dsi-progress-logger = "0.3.0"
env_logger = "0.11.6"
human_bytes = "0.4.3"
log = "0.4.25"
swh-graph = "6.3.1"
