{
 "title": "Cassandra",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client request timeout",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_clientrequest_timeouts_count[$__rate_interval]) >0",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Oversized mutations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_commitlog_oversizedmutations_count",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Data occupation per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused) by (instance)",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Commitlog size  per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_commitlog_totalcommitlogsize",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending  Hints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_totalhintsinprogress_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total hints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_totalhints_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending  Compaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_pendingcompactions{keyspace=''}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "partition size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_maxpartitionsize{keyspace=\"\"} > 0"
    }
   ]
  },
  {
   "title": "Repair job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_repairjobsstarted - cassandra_table_repairjobscompleted",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}