{
 "title": "Run statistics",
 "time": { "from": "2021-07-05T17:28:00.000Z", "to": "2021-07-06T06:50:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "objects",
    "query": {
     "query": "label_values(swh_objects_total, type)"
    }
   },
   {
    "name": "cassandra",
    "query": {
     "query": "label_values(swh_objects_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Run Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${__to} - ${__from}" }
   ]
  },
  {
   "title": "Run Duration in s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(${__to} - ${__from}) / 1000" }
   ]
  },
  {
   "title": "Client timeouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_clientrequest_timeouts_count)"
    }
   ]
  },
  { "title": "${objects}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "objects" },
  {
   "title": "Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(swh_objects_total{instance=~\"${cassandra}\", type=~\"${objects}\"})"
    }
   ]
  },
  {
   "title": "Avg creation rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(swh_objects_total{instance=~\"${cassandra}\", type=~\"${objects}\"}) / (${__to} - ${__from}) * 1000"
    }
   ]
  }
 ]
}