---
# - name: "Get public ipv4 address"
#   set_fact:
#     cassandra_seed_ips: "{{ansible_facts[item]['ipv4']['address']}}"
#   with_items:
#     - "{{cassandra_listen_interface }}"

- name: Install cassandra signing key
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present

- name: Install cassandra apt repository
  apt_repository:
    repo: deb http://downloads.apache.org/cassandra/debian 40x main
    state: present
    filename: cassandra.sources

- name: Install cassandra packages
  apt:
    update_cache: true # force an apt update before
    name:
      ## TODO: check other version than jdk11
      - cassandra
      - dstat
      - facter
      - openjdk-11-jdk
      - smartmontools
      - tcpdump

- name: install prometheus node exporter
  include: _install_prometheus_exporter.yml

- name: Create datadirs
  file:
    state: directory
    path: "{{ item }}"
    owner: "cassandra"
    group: "cassandra"
    mode: "0755"
    recurse: true
  with_items:
    - "{{ cassandra_data_dir_base }}"
    - "{{ cassandra_data_dir_system }}"
    - "{{ cassandra_data_dir }}"
    - "{{ cassandra_commitlogs_dir }}"

- name: Download prometheus jmx exporter
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
    dest: /opt/jmx_prometheus_javaagent-0.15.0.jar

- name: Download prometheus exporter configuration
  get_url:
    url: https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/cassandra.yml
    dest: /opt/jmx_exporter.yml

- name: Configure cassandra
  template:
    src: "templates/{{item}}"
    dest: "{{cassandra_config_dir}}/{{item}}"
  with_items: [cassandra.yaml, jvm11-server.options]
  register: cassandra_configuration_files

- name: Restart cassandra service
  service:
    name: cassandra
    state: restarted
  when: cassandra_configuration_files.changed

- name: cassandra replication configuration script
  template:
    src: templates/swhstorage/change-cassandra-replication.sh
    dest: /usr/local/bin/change-cassandra-replication.sh
    mode: 0755

  # TODO test different read ahead

- name: Install object count exporter
  copy:
    src: "files/cassandra/prometheus-object-count.sh"
    dest: "/usr/local/bin/prometheus-object-count.sh"
    owner: root
    group: root
    mode: "0755"

- name: Send object count to prometheus
  cron:
    name: "object count"
    minute: "*"
    hour: "*"
    job: "/usr/local/bin/prometheus-object-count.sh > /dev/null"
