---
# - name: "Get public ipv4 address"
#   set_fact:
#     cassandra_seed_ips: "{{ansible_facts[item]['ipv4']['address']}}"
#   with_items:
#     - "{{cassandra_listen_interface }}"

- name: Install cassandra signing key
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present

- name: Install cassandra apt repository
  apt_repository:
    repo: deb http://downloads.apache.org/cassandra/debian 40x main
    state: present
    filename: cassandra.sources

- name: Install cassandra packages
  apt:
    update_cache: true # force an apt update before
    name:
      ## TODO: check other version than jdk11
      - openjdk-11-jdk
      - cassandra
      - dstat
      - smartmontools
      - facter

- name: Create datadirs
  file:
    state: directory
    path: "{{ item }}"
    owner: "cassandra"
    group: "cassandra"
    mode: "0755"
  with_items:
    - "{{ cassandra_data_dir_base }}"
    - "{{ cassandra_data_dir_system }}"
    - "{{ cassandra_data_dir }}"
    - "{{ cassandra_commitlogs_dir }}"

- name: Configure cassandra
  template:
    src: "templates/{{item}}"
    dest: "{{cassandra_config_dir}}/{{item}}"
  with_items: [cassandra.yaml, jvm.options]
  register: cassandra_configuration_files

- name: Restart cassandra service
  service:
    name: cassandra
    state: restarted
  when: cassandra_configuration_files.changed



  # TODO test different read ahead
