# Global configuration
monitoring:
  hosts:
    monitoring1:
    paranoia-3.rennes.grid5000.fr:
    parasilo-[18:19].rennes.grid5000.fr:
    paravance-[1:9].rennes.grid5000.fr:
    troll-1.grenoble.grid5000.fr:
  vars:
    ansible_connection: local
    install_docker_install_script: false

swh-storage:
  hosts:
    parasilo-[20:28].rennes.grid5000.fr:
    paravance-[10:78].rennes.grid5000.fr:
    troll-[2:4].grenoble.grid5000.fr:
    # local vagrant hosts
    swh-storage1:
  vars:
      ansible_connection: local
      journal:
        brokers:
          - broker1.journal.softwareheritage.org:9093
          - broker2.journal.softwareheritage.org:9093
          - broker3.journal.softwareheritage.org:9093
          - broker4.journal.softwareheritage.org:9093   
        consumer:
          user: swh-vse
          group: swh-vse-grid5000-1
        replayer_count:
          content: 60
          skipped_content: 1
          directory: 60
          extid: 5
          origin: 1
          origin_visit: 1
          origin_visit_status: 1
          release: 1
          revision: 1
          snapshot: 1
          # Initial backfill
          # content: 20
          # skipped_content: 2
          # directory: 20
          # origin: 20
          # origin_visit: 20
          # origin_visit_status: 20
          # release: 20
          # revision: 20
          # snapshot: 20

cassandra:
  hosts:
    dahu-[1:32].grenoble.grid5000.fr:
    parasilo-[1:17].rennes.grid5000.fr:
    # local vagrant hosts
    cassandra[1:9]:
  vars:
    ansible_connection: local
    cassandra_config_dir: /etc/cassandra
    cassandra_data_dir_base: /srv/cassandra
    cassandra_data_dir_system: "{{cassandra_data_dir_base}}/system"
    cassandra_data_dir: "{{ cassandra_data_dir_base }}/data"
    cassandra_commitlogs_dir: "{{ cassandra_data_dir_base }}/commitlogs"


# Per cluster specificities
dahu_cluster_hosts:
  hosts:
    dahu-[1:32].grenoble.grid5000.fr:
  vars:
    cassandra_listen_interface: enp24s0f0
    zfs_pools:
      commitlogs:
        disks:
          - sdb
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - sdc
        datasets:
          data: /srv/cassandra/data

parasilo_cluster_hosts:
  hosts:
    parasilo-[1:28].rennes.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    ## run 1/2/3 CL on SSD + data on HDDS
    zfs_pools:
      commitlogs:
        disks:
          - sdf
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - sdb
          - sdc
          - sdd
          - sde
        datasets:
          data: /srv/cassandra/data
    ## run 4 CL and data on same partition
    # zfs_pools:
    #   data:
    #     disks:
    #       - sdb
    #       - sdc
    #       - sdd
    #       - sde
    #     datasets:
    #       data: /srv/cassandra
    #   foo: # workaround
    #     disks:
    #       - sdf
    #     datasets:
    #       foo: /srv/foo
    ## run 5: CL on SSD + data on 2 HDD
    # zfs_pools:
    #   commitlogs:
    #     disks:
    #       - sdf
    #     datasets:
    #       commitlogs: /srv/cassandra/commitlogs
    #   data:
    #     disks:
    #       - sdc
    #       - sdd
    #     datasets:
    #       data: /srv/cassandra/data
    ## run 6: CL on HDD + data on 2 HDD
    # zfs_pools:
    #   commitlogs:
    #     disks:
    #       - sdb
    #     datasets:
    #       commitlogs: /srv/cassandra/commitlogs
    #   data:
    #     disks:
    #       - sdc
    #       - sdd
    #     datasets:
    #       data: /srv/cassandra/data


paravance_cluster_hosts:
  hosts:
    paravance-[1:78].rennes.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    zfs_pools:
      - data:
          disks:
            - sdb
          datasets:
            data: /srv/cassandra

# Vagrant configuration
vagrant_nodes:
  hosts:
    cassandra1:
      ansible_host: 10.168.180.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra1/libvirt/private_key
    cassandra2:
      ansible_host: 10.168.180.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
    cassandra3:
      ansible_host: 10.168.180.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra3/libvirt/private_key
    swh-storage1:
      ansible_host: 10.168.180.14
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/swh-storage/libvirt/private_key
    monitoring1:
      ansible_host: 10.168.180.15
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/monitoring/libvirt/private_key
  vars:
    ansible_connection: ssh
    install_docker_install_script: true
    journal:
      brokers:
      # staging
        - broker0.journal.staging.swh.network:9093
      consumer:
        user: swh-vse
        group: swh-vse-grid5000-1
      replayer_count:
        content: 0
        skipped_content: 0
        directory: 5
        origin: 0
        origin_visit: 0
        origin_visit_status: 0
        release: 0
        revision: 0
        snapshot: 0
    cassandra_listen_interface: eth1
    # passed through --extra-vars on grid5000
    cassandra_seed_ips: 10.168.180.11,10.168.180.12,10.168.180.13
    nodes: 10.168.180.11,10.168.180.12,10.168.180.13,10.168.180.14,10.168.180.15,test
    zfs_pools:
      commitlogs:
        disks:
          - vdb
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - vdc
          - vdd
        datasets:
          data: /srv/cassandra/data
