# Global configuration
zfs:
  hosts:
    parasilo-19.rennes.grid5000.fr:
    monitoring1:

monitoring:
  hosts:
    monitoring1:
    paranoia-3.rennes.grid5000.fr:
    parasilo-[18:19].rennes.grid5000.fr:
      federated_prometheus: 
        - gros-124.nancy.grid5000.fr:9090
    paravance-[1:9].rennes.grid5000.fr:
    troll-1.grenoble.grid5000.fr:
    gros-[100:124].nancy.grid5000.fr:
  vars:
    ansible_connection: local
    install_docker_install_script: false

swh-storage:
  hosts:
    parasilo-[20:28].rennes.grid5000.fr:
    paravance-[10:78].rennes.grid5000.fr:
    troll-[2:4].grenoble.grid5000.fr:
    # local vagrant hosts
    swh-storage1:
  vars:
      ansible_connection: local
      journal:
        brokers:
          - broker1.journal.softwareheritage.org:9093
          - broker2.journal.softwareheritage.org:9093
          - broker3.journal.softwareheritage.org:9093
          - broker4.journal.softwareheritage.org:9093   
        consumer:
          user: swh-vse
          group: swh-vse-grid5000-1
        replayer_count:
          content: 10
          skipped_content: 1
          directory: 10
          extid: 1
          origin: 1
          origin_visit: 1
          origin_visit_status: 1
          release: 1
          revision: 1
          snapshot: 1
          # Initial backfill
          # content: 20
          # skipped_content: 2
          # directory: 20
          # origin: 20
          # origin_visit: 20
          # origin_visit_status: 20
          # release: 20
          # revision: 20
          # snapshot: 20

cassandra:
  hosts:
    dahu-[1:32].grenoble.grid5000.fr:
    parasilo-[1:17].rennes.grid5000.fr:
      cassandra_datacenter: datacenter1
    # local vagrant hosts
    cassandra[1:9]:
    gros-[1:99].nancy.grid5000.fr:
      cassandra_datacenter: datacenter2
      cassandra_disk_optimization: ssd
  vars:
    ansible_connection: local
    cassandra_config_dir: /etc/cassandra
    cassandra_data_dir_base: /srv/cassandra
    cassandra_data_dir_system: "{{cassandra_data_dir_base}}/system"
    cassandra_data_dir: "{{ cassandra_data_dir_base }}/data"
    cassandra_commitlogs_dir: "{{ cassandra_data_dir_base }}/commitlogs"
    cassandra_rack: rack1
    cassandra_memory: 16G
    cassandra_disk_optimization: spinning

# Per cluster specificities
dahu_cluster_hosts:
  hosts:
    dahu-[1:32].grenoble.grid5000.fr:
  vars:
    cassandra_listen_interface: enp24s0f0
    zfs_pools:
      commitlogs:
        disks:
          - sdb
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - sdc
        datasets:
          data: /srv/cassandra/data

gros_cluster_hosts:
  hosts:
    gros-[1:124].nancy.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    zfs_pools:
      data:
        disks:
          - sdb
        datasets:
          data: /srv/cassandra

parasilo_scheduler_db:
  hosts:
    parasilo-19.rennes.grid5000.fr:
  vars:
    zfs_pools:
      data:
        disks:
          - sdb
          - sdc
          - sdd
          - sde
        datasets:
          data: /srv/data


parasilo_cluster_hosts:
  hosts:
    parasilo-[1:28].rennes.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    ## run 1/2/3 CL on SSD + data on HDDS
    zfs_pools:
      commitlogs:
        disks:
          - sdf
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - sdb
          - sdc
          - sdd
          - sde
        datasets:
          data: /srv/cassandra/data
    ## run 4 CL and data on same partition
    # zfs_pools:
    #   data:
    #     disks:
    #       - sdb
    #       - sdc
    #       - sdd
    #       - sde
    #     datasets:
    #       data: /srv/cassandra
    #   foo: # workaround
    #     disks:
    #       - sdf
    #     datasets:
    #       foo: /srv/foo
    ## run 5: CL on SSD + data on 2 HDD
    # zfs_pools:
    #   commitlogs:
    #     disks:
    #       - sdf
    #     datasets:
    #       commitlogs: /srv/cassandra/commitlogs
    #   data:
    #     disks:
    #       - sdc
    #       - sdd
    #     datasets:
    #       data: /srv/cassandra/data
    ## run 6: CL on HDD + data on 2 HDD
    # zfs_pools:
    #   commitlogs:
    #     disks:
    #       - sdb
    #     datasets:
    #       commitlogs: /srv/cassandra/commitlogs
    #   data:
    #     disks:
    #       - sdc
    #       - sdd
    #     datasets:
    #       data: /srv/cassandra/data


paravance_cluster_hosts:
  hosts:
    paravance-[1:78].rennes.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    zfs_pools:
      - data:
          disks:
            - sdb
          datasets:
            data: /srv/cassandra

# Vagrant configuration
vagrant_nodes:
  hosts:
    cassandra1:
      ansible_host: 10.168.180.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra1/libvirt/private_key
    cassandra2:
      ansible_host: 10.168.180.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
    cassandra3:
      ansible_host: 10.168.180.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra3/libvirt/private_key
    cassandra4:
      ansible_host: 10.168.180.24
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra3/libvirt/private_key
      cassandra_datacenter: datacenter2
    swh-storage1:
      ansible_host: 10.168.180.14
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/swh-storage/libvirt/private_key
    monitoring1:
      ansible_host: 10.168.180.15
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/monitoring/libvirt/private_key
      federated_prometheus:
        - monitoring2
  vars:
    ansible_connection: ssh
    install_docker_install_script: true
    cassandra_memory: 1G
    cassandra_datacenter: datacenter1
    cassandra_rack: rack1
    journal:
      brokers:
      # staging
        - broker0.journal.staging.swh.network:9093
      consumer:
        user: swh-vse
        group: swh-vse-grid5000-1
      replayer_count:
        content: 1
        extid: 1
        skipped_content: 1
        directory: 1
        origin: 1
        origin_visit: 1
        origin_visit_status: 1
        release: 1
        revision: 1
        snapshot: 1
    cassandra_listen_interface: eth1
    # passed through --extra-vars on grid5000
    cassandra_seed_ips: 10.168.180.11,10.168.180.12,10.168.180.13
    nodes: 10.168.180.11,10.168.180.12,10.168.180.13,10.168.180.14,10.168.180.15,test
    zfs_pools:
      commitlogs:
        disks:
          - vdb
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - vdc
          - vdd
        datasets:
          data: /srv/cassandra/data
