# Global configuration
cassandra:
  hosts:
    dahu-[1:32].grenoble.grid5000.fr:
    parasilo-[2:4].rennes.grid5000.fr:
    # local vagrant hosts
    cassandra[1:9]:
  vars:
    ansible_connection: local
    cassandra_config_dir: /etc/cassandra
    cassandra_data_dir_base: /srv/cassandra
    cassandra_data_dir_system: "{{cassandra_data_dir_base}}/system"
    cassandra_data_dir: "{{ cassandra_data_dir_base }}/data"
    cassandra_commitlogs_dir: "{{ cassandra_data_dir_base }}/commitlogs"


# Per cluster specificities
dahu_cluster_hosts:
  hosts:
    dahu[1:32].grenoble.grid5000.fr
  vars:
    cassandra_listen_interface: enp24s0f0

parasilo_cluster_hosts:
  hosts:
    parasilo-[1:28].rennes.grid5000.fr:
  vars:
    cassandra_listen_interface: eno1
    zfs_pools:
      commitlogs:
        disks:
          - sdf
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - sdb
          - sdc
          - sdd
          - sde
        datasets:
          data: /srv/cassandra/data


# Vagrant configuration
vagrant_nodes:
  hosts:
    cassandra1:
      ansible_host: 10.168.180.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra1/libvirt/private_key
    cassandra2:
      ansible_host: 10.168.180.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
    cassandra3:
      ansible_host: 10.168.180.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
  vars:
    ansible_connection: ssh
    cassandra_listen_interface: eth1
    # passed through --extra-vars on grid5000
    cassandra_seed_ips: 10.168.180.11,10.168.180.12,10.168.180.13
    zfs_pools:
      commitlogs:
        disks:
          - vdb
        datasets:
          commitlogs: /srv/cassandra/commitlogs
      data:
        disks:
          - vdc
          - vdd
        datasets:
          data: /srv/cassandra/data
