cassandra:
  hosts:
    dahu[1:32].grenoble.grid5000.fr:
    # local vagrant hosts
    cassandra[1:9]:
  vars:
    cassandra_config_dir: /etc/cassandra
    cassandra_data_dir_base: /srv/cassandra
    cassandra_data_dir_system: "{{cassandra_data_dir_base}}/system"
    cassandra_data_dir: "{{ cassandra_data_dir_base }}/data"
    cassandra_commitlogs_dir: "{{ cassandra_data_dir_base }}/commitlogs"

vagrant_nodes:
  hosts:
    cassandra1:
      ansible_host: 10.168.180.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra1/libvirt/private_key
    cassandra2:
      ansible_host: 10.168.180.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
    cassandra3:
      ansible_host: 10.168.180.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/cassandra2/libvirt/private_key
  vars:
    cassandra_listen_interface: eth1
    # passed through --extra-vars on grid5000
    cassandra_seed_ips: 10.168.180.11,10.168.180.12,10.168.180.13

dahu_cluster_hosts:
  hosts:
    dahu[1:32].grenoble.grid5000.fr
  vars:
    cassandra_listen_interface: enp24s0f0
