---
- name: Common
  hosts: all
  tasks:
    - include: common.yml

- name: Install cassandra
  hosts: cassandra
  tasks:
    - include: zfs.yml
    - include: cassandra.yml

- name: Install SWH Storage
  hosts: swh-storage
  tasks:
    - include: swh-storage.yml

- name: Install Monitoring
  hosts: monitoring
  tasks:
    - include: monitoring.yml
