---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  labels:
    name: d3
spec:
  rules:
    - host: demo
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: d3-clusterip
                port:
                  number: 5000
