# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: d3-pv
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: d3-pv
#   local:
#     path: /srv/d3
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         # TODO adapt for your needs
#         - key: kubernetes.io/os
#           operator: In
#           values:
#           - vs3-k3s-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3
spec:
  selector:
    matchLabels:
      app: d3
  replicas: 5
  strategy: 
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: d3
    spec:
      containers:
      - name: d3
        image: registry.demo/demo:v2
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            port: 5000
          periodSeconds: 2
          failureThreshold: 1          
        startupProbe:
          httpGet:
            port: 5000
          periodSeconds: 2
          successThreshold: 1
        livenessProbe:
          httpGet:
            port: 5000
          periodSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        volumeMounts:
        - name: pvc
          mountPath: /data
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: d3-pvc
