volumes:
  grafana-data:

services:
  prometheus:
    build: 
      context: prometheus
      args:
        FEDERATED_PROMETHEUS_IP: ${FEDERATED_PROMETHEUS_IP}

    volumes:
      - ${PROMETHEUS_DATA_DIR}:/prometheus
    ports:
      - 9092:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 80:3000
    environment:
      GF_SERVER_ROOT_URL: http://localhost:9093/
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "grafana-data:/var/lib/grafana"
