---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: web-db
  local:
    path: /srv/data/softwareheritage-kube/web-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: web-db
  resources:
    requests:
      storage: 10Gi

---
## TODO Change this to your real postgresql password
apiVersion: v1
kind: Secret
metadata:
  name: web-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: swh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-db
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_USER: swh
  POSTGRES_DB: swh-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-db
  labels:
    app: web-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-db
  template:
    metadata:
      labels:
        app: web-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storage
                operator: In
                values:
                - 'true'
      containers:
      - name: web-db
        image: postgres:13.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        args:
          - "-c"
          - "shared_buffers=5GB"
          - "-c"
          - "effective_cache_size=2GB"
          - "-c"
          - "random_page_cost=1.5"
          - "-c"
          - "max_wal_size=1GB"
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: web-db
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-db
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: web-db
                key: POSTGRES_DB
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: web-db-pvc
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
      volumes:
        - name: web-db-pvc
          persistentVolumeClaim:
            claimName: web-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-db
spec:
  type: NodePort
  selector:
    app: web-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32437
