#!/usr/bin/perl
# -*- cperl -*-
#
# Copyright (C) 2015 Nicolas Dandrimont <nicolas@dandrimont.eu>
#               2016 Stefano Zacchiroli <zack@upsilon.cc>
#               2018 Antoine R. Dumont (@ardumont) <antoine.romain.dumont@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

=head1 NAME

softwareheritage_indexer - Plugin to monitor the number of Softwareheritage indexer counter status

=head1 CONFIGURATION

Configuration is done through libpq environment variables, for example
PGUSER, PGDATABASE, etc. For more information, see L<Munin::Plugin::Pgsql>.

=head1 SEE ALSO

L<Munin::Plugin::Pgsql>

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=head1 AUTHOR

Stefano Zacchiroli <zack@upsilon.cc>

=head1 COPYRIGHT/License

Nicolas Dandrimont <nicolas@dandrimont.eu>

All rights reserved. This program is free software; you can
redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; version 2
dated June, 1991.

=cut

use strict;
use warnings;

use Munin::Plugin::Pgsql;

# Pre-requisite:
# root@somerset:~# cat /etc/munin/plugin-conf.d/softwareheritage
# [softwareheritage-indexer]
# user postgres
# env.PGUSER postgres
# env.PGPORT 5434


my $pg = Munin::Plugin::Pgsql->new(
    defaultdb   => 'softwareheritage-indexer',
    category    => 'SoftwareHeritage',
    title       => 'Software Heritage Indexer Counter',
    info        => 'Count the Indexer scheduled in Software Heritage Indexer database',
    vlabel      => 'Indexer Type',
    basequery   => "(select 'mimetype' as nature, count(*) from content_mimetype union select 'fossology_license' as nature, count(*) from content_fossology_license)",
    configquery => "VALUES
        ('mimetype', 'Mimetype'),
        ('fossology_license', 'Fossology License')
    ",
    base        => 1000000,
    extraconfig => 'graph_args --step 3600 --lower-limit 2000000000',
);

$pg->Process();
